name: execute-shell-scripts

on:
    push

jobs:
    shell_script_job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4.1.7    

            - name: List all files
              run: ls -ltra
            
            - name: Execute shell script 
              run: ./ascii-script.sh  