name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "Welcome to Github Actions Demo"

            - name: List files
              run: ls -l
              
            - name: Read files
              run: cat ..\README.md  