name: Workflow filters and Activities

on:
    workflow_dispatch: 
    # schedule:
    #     - cron: "*/2 * * * *"

    push:
        # branches-ignore: 
        #     - feature/*     # feature/abc, feature/xyz
        #     - test/**       # test/a/b, test/x/y
        branches: 
            - main
            - '!feature/*'
    pull_request: 
        types:
            - opened
            - closed
        paths-ignore:          # workflow will only run when a pull request that includes change on any file other than the README.md
            - README.md
        branches: 
            - main

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo this workflo/job/step is executed for event type - ${{github.event_name}}